# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"check_img": "10_utils.ipynb",
         "clean_error_img": "10_utils.ipynb",
         "hush": "10_utils.ipynb",
         "CosineSearch": "15_interp_latent.ipynb",
         "InterpEmbeddings": "15_interp_latent.ipynb",
         "ImageLabeler": "20_Image_Labeler.ipynb",
         "SingleClassImageLabeler": "20_Image_Labeler.ipynb",
         "MultiClassImageLabeler": "20_Image_Labeler.ipynb",
         "no_missing_values": "35_tabular_data.ipynb",
         "plot_hist": "35_tabular_data.ipynb",
         "Textual": "41_nlp_data.ipynb",
         "InterpEmbeddingsTokenizer": "45_nlp_interp.ipynb"}

modules = ["utils.py",
           "interp/latent.py",
           "interp/__init__.py",
           "turk/image.py",
           "tabular/data.py",
           "tabular/__init__.py",
           "nlp/data.py",
           "nlp/interp.py",
           "nlp/__init__.py"]

doc_url = "https://unpackai.github.io/unpackai/"

git_url = "https://github.com/unpackai/unpackai/tree/master/"

def custom_doc_links(name): return None
