# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/18_interp.ipynb (unless otherwise specified).

__all__ = []

# Cell
from ..utils import hush
from ..bug import ishell, BUGBOOK
from .latent import CosineSearch, InterpEmbeddings